# Jekyll configuration file
#
# References:
#
# * Configuration | Jekyll • Simple, blog-aware, static sites
#   https://jekyllrb.com/docs/configuration/
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

url: https://brlin.gitlab.io
baseurl: ''

theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - continuous-integration/
  - docker-compose.yaml
  - .github/
  - LICENSES/
  - README.md
  - '**/README.md'
  - REUSE.toml
  - '**/REUSE.toml'
